spring:
  output.ansi.enabled: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/study-inflearn/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  #  root: info
  org.hibernate.SQL: debug